# docker-compose-optimized.yml
# Minimal ClickHouse-only setup for optimized real-time ingestion pipeline
# Eliminates Kafka/Zookeeper stack for 70% memory reduction

services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: clickhouse-optimized
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch_data_optimized:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=password
      - CLICKHOUSE_DB=mexc_data
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "clickhouse-client", "-q", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  ch_data_optimized: