services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: mexc-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse.xml:/etc/clickhouse-server/config.d/custom-config.xml:ro
    environment:
      CLICKHOUSE_DB: mexc_data
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - mexc-network

  # Database setup service - runs once to initialize tables
  setup:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mexc-setup
    user: "1000:1000"
    environment:
      - CONTAINER_TYPE=setup
      - CLICKHOUSE_HOST=clickhouse
    depends_on:
      clickhouse:
        condition: service_healthy
    command: python3 setup_database.py
    networks:
      - mexc-network
    restart: "no"  # Only run once

  # BTC client with proxy separation
  btc-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mexc-btc-client
    user: "1000:1000"
    environment:
      - CONTAINER_TYPE=btc-client
      - CLICKHOUSE_HOST=clickhouse
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on:
      setup:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
    command: python3 client_btc.py
    networks:
      - mexc-network
    restart: unless-stopped
    # Add startup delay to ensure setup is complete
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('https://ipinfo.io/ip', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ETH client with proxy separation
  eth-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mexc-eth-client
    user: "1000:1000"
    environment:
      - CONTAINER_TYPE=eth-client
      - CLICKHOUSE_HOST=clickhouse
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on:
      setup:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
    command: python3 client_eth.py
    networks:
      - mexc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('https://ipinfo.io/ip', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # SOL client with proxy separation
  sol-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mexc-sol-client
    user: "1000:1000"
    environment:
      - CONTAINER_TYPE=sol-client
      - CLICKHOUSE_HOST=clickhouse
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on:
      setup:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
    command: python3 client_sol.py
    networks:
      - mexc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('https://ipinfo.io/ip', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Hourly data exporter service
  exporter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mexc-exporter
    user: "1000:1000"
    environment:
      - CONTAINER_TYPE=exporter
      - CLICKHOUSE_HOST=clickhouse
      - EXPORT_DEBUG_MODE=true  # Set to 'false' for production hourly mode
    volumes:
      - ./exports:/exports  # Mount local exports directory
    depends_on:
      clickhouse:
        condition: service_healthy
      setup:
        condition: service_completed_successfully
    command: python3 hourly_exporter.py
    networks:
      - mexc-network
    restart: unless-stopped

volumes:
  clickhouse_data:
    driver: local

networks:
  mexc-network:
    driver: bridge