services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: mexc-clickhouse
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native client interface
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./clickhouse-config-simple.xml:/etc/clickhouse-server/config.d/custom-config.xml:ro
    environment:
      CLICKHOUSE_DB: mexc_data
      CLICKHOUSE_USER: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - mexc-network

  # Database setup service - runs once to initialize tables
  setup:
    build: .
    container_name: mexc-setup
    environment:
      - CONTAINER_TYPE=setup
      - CLICKHOUSE_HOST=clickhouse
    depends_on:
      clickhouse:
        condition: service_healthy
    command: python3 ch_setup.py
    networks:
      - mexc-network
    restart: "no"  # Only run once

  # BTC client with VPN - for testing single client first
  btc-client:
    build: .
    container_name: mexc-btc-client
    environment:
      - CONTAINER_TYPE=btc-client
      - CLICKHOUSE_HOST=clickhouse
      # VPN Configuration (configure these with your NordVPN credentials)
      - NORDVPN_USER=${NORDVPN_USER:-}
      - NORDVPN_PASS=${NORDVPN_PASS:-}
      - NORDVPN_COUNTRY=United_States
      - NORDVPN_PROTOCOL=nordlynx
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on:
      setup:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
    command: python3 btcdat.py
    networks:
      - mexc-network
    restart: unless-stopped
    # Add startup delay to ensure setup is complete
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('https://ipinfo.io/ip', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # ETH client with UK VPN
  eth-client:
    build: .
    container_name: mexc-eth-client
    environment:
      - CONTAINER_TYPE=eth-client
      - CLICKHOUSE_HOST=clickhouse
      - NORDVPN_USER=${NORDVPN_USER:-}
      - NORDVPN_PASS=${NORDVPN_PASS:-}
      - NORDVPN_COUNTRY=United_Kingdom
      - NORDVPN_PROTOCOL=nordlynx
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on:
      setup:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
    command: python3 ethdat.py
    networks:
      - mexc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('https://ipinfo.io/ip', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # SOL client with Canadian VPN
  sol-client:
    build: .
    container_name: mexc-sol-client
    environment:
      - CONTAINER_TYPE=sol-client
      - CLICKHOUSE_HOST=clickhouse
      - NORDVPN_USER=${NORDVPN_USER:-}
      - NORDVPN_PASS=${NORDVPN_PASS:-}
      - NORDVPN_COUNTRY=Canada
      - NORDVPN_PROTOCOL=nordlynx
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun:/dev/net/tun
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
      - net.ipv6.conf.all.disable_ipv6=0
    depends_on:
      setup:
        condition: service_completed_successfully
      clickhouse:
        condition: service_healthy
    command: python3 soldat.py
    networks:
      - mexc-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python3", "-c", "import requests; requests.get('https://ipinfo.io/ip', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  clickhouse_data:
    driver: local

networks:
  mexc-network:
    driver: bridge